server:
  port: 8090


spring:
  rabbitmq:
    host: 192.168.250.134
    port: 5672
    username: foxmo
    password: foxmo
    publisher-confirm-type: correlated
    publisher-returns: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
